version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "gradle"
    directory: "/"
    open-pull-requests-limit: 15
    schedule:
      interval: "daily"

  - package-ecosystem: "gradle"
    directory: "/buildSrc"
    open-pull-requests-limit: 15
    schedule:
      interval: "daily"
