# Adapted from https://doc.mergify.io/examples.html#running-ci-pipelines-automatically
# Validate your changes with:
#   $ curl -F 'data=@.mergify.yml' https://gh.mergify.io/validate/

pull_request_rules:
  - name: Automatic merges for Dependabot pull requests
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - check-success=acceptance_tests (26)
      - check-success=acceptance_tests (27)      
      - check-success=acceptance_tests (28)
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: squash

  - name: Automatic merges for Dotanukibot pull requests
    conditions:
      - author~=^dotanukibot
      - check-success=acceptance_tests (26)
      - check-success=acceptance_tests (27) 
      - check-success=acceptance_tests (28)
    actions:
      merge:
        method: squash

  - name: Be author's friend
    conditions:
      - author~=^ubiratansoares
      - check-success=acceptance_tests (26)
      - check-success=acceptance_tests (27) 
      - check-success=acceptance_tests (28)
    actions:
      merge:
        method: squash
