include(
    ":app",
    ":domain",
    ":logger",
    ":coroutines-testutils",
    ":networking",
    ":persistance",
    ":rest-chucknorris",
    ":unidirectional-dataflow",
    ":shared-assets",
    ":shared-utilities",
    ":facts",
    ":search",
    ":onboarding",
    ":navigator"
)