-dontwarn io.dotanuki.norris.platform.android.core.assets.R$color
-dontwarn io.dotanuki.norris.platform.android.core.assets.R$drawable
-dontwarn io.dotanuki.norris.platform.android.core.assets.R$string
