build:
  maxIssues: 0
  excludeCorrectable: false

config:
  validation: true
  warningsAsErrors: false


performance:
  active: true
  SpreadOperator:
    active: false

exceptions:
  active: true
  TooGenericExceptionCaught:
    active: false

style:
  active: true
  MagicNumber:
    active: false
