name: "Setup Android build"
description: "Common steps before running a Gradle command, regarding the Runner OS"

runs:
  using: "composite"
  steps:
      - name: Setup JDK
        id: setup-jdk
        uses: actions/setup-java@v4.2.1
        with:
            distribution: 'zulu'
            java-version: '21'

      - name: Optimize for Gradle build
        shell: bash
        run: ${{ github.action_path }}/setup-gradle-properties.sh ${{ steps.setup-jdk.outputs.path }}

      - name: Generate new Android Debug Keystore
        shell: bash
        run: ${{ github.action_path }}/setup-android-keystore.sh

      - name: Setup Dependency Submission
        uses: gradle/actions/dependency-submission@v3.3.0

      - name: Setup Cache
        uses: gradle/actions/setup-gradle@v3.3.0
        with:
          gradle-home-cache-strict-match: false
          gradle-home-cache-cleanup: true
