name: "Setup Android build"
description: "Common steps before running a Gradle command, regarding the Runner OS"

inputs:
  norris-key:
    description: “GPG key required to decript local files”
    required: true

runs:
  using: "composite"
  steps:
      - name: Setup JDK
        uses: actions/setup-java@v3.4.1
        with:
          distribution: 'temurin'
          java-version: 11

      - name: Setup Cache
        uses: actions/cache@v3.0.6
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-${{ github.job }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/gradle/libs.versions.toml') }}
          restore-keys: ${{ runner.os }}-${{ github.job }}-

      - name: Optimize for Gradle build
        shell: bash
        run: ${{ github.action_path }}/setup-gradle-properties.sh

      - name: Extract credentials
        shell: bash      
        run: ./scripts/secrets.sh decrypt ${{ inputs.norris-key }}

