name: "Setup Android build"
description: "Common steps before running a Gradle command, regarding the Runner OS"

inputs:
  norris-key:
    description: “GPG key required to decript local files”
    required: true

runs:
  using: "composite"
  steps:
      - name: Setup Cache
        uses: gradle/gradle-build-action@v2.3.3
        with:
          generate-job-summary: false
          gradle-home-cache-strict-match: true
          gradle-home-cache-cleanup: true

      - name: Optimize for Gradle build
        shell: bash
        run: ${{ github.action_path }}/setup-gradle-properties.sh

      - name: Extract credentials
        shell: bash      
        run: ./scripts/secrets.sh decrypt ${{ inputs.norris-key }}
