name: "Setup Android build"
description: "Common steps before running a Gradle command, regarding the Runner OS"

inputs:
  norris-key:
    description: "Private key required to decript local files"
    required: true

runs:
  using: "composite"
  steps:
      - name: Setup JDK
        id: setup-jdk
        uses: actions/setup-java@v3.6.0
        with:
            distribution: 'zulu'
            java-version: '17'

      - name: Optimize for Gradle build
        shell: bash
        run: ${{ github.action_path }}/setup-gradle-properties.sh ${{ steps.setup-jdk.outputs.path }}

      - name: Generate new Android Debug Keystore
        shell: bash
        run: mkdir -p $HOME/.android && keytool -dname "cn=Ubiratan Soares, ou=Dotanuki, o=Dotanuki, l=Barcelona, st=Catalonia, c=ES" -genkey -v -keystore $HOME/.android/debug.keystore -storepass android -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 10000

      - name: Setup Cache
        uses: gradle/gradle-build-action@v2.3.3
        with:
          generate-job-summary: false
          gradle-home-cache-strict-match: true
          gradle-home-cache-cleanup: true
